import type { Character } from '@/types';

export const charactersMock: Character[] = [
  {
    created: '2017-11-04T18:48:46.250Z',
    episode: ['https://rickandmortyapi.com/api/episode/1'],
    gender: 'Male',
    id: 1,
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    location: { name: 'Mock Citadel of Ricks', url: 'https://rickandmortyapi.com/api/location/3' },
    name: 'Mock Rick Sanchez',
    origin: { name: 'Mock Earth (C-137)', url: 'https://rickandmortyapi.com/api/location/1' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/1',
  },
  {
    created: '2017-11-04T18:50:21.651Z',
    episode: ['https://rickandmortyapi.com/api/episode/1'],
    gender: 'Male',
    id: 2,
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    location: { name: 'Mock Citadel of Ricks', url: 'https://rickandmortyapi.com/api/location/3' },
    name: 'Mock Morty Smith',
    origin: { name: 'Mock unknown', url: '' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/2',
  },
  {
    created: '2017-11-04T19:09:56.428Z',
    episode: ['https://rickandmortyapi.com/api/episode/6'],
    gender: 'Female',
    id: 3,
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Summer Smith',
    origin: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/3',
  },
  {
    created: '2017-11-04T19:22:43.665Z',
    episode: ['https://rickandmortyapi.com/api/episode/6'],
    gender: 'Female',
    id: 4,
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Beth Smith',
    origin: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/4',
  },
  {
    created: '2017-11-04T19:26:56.301Z',
    episode: ['https://rickandmortyapi.com/api/episode/6', 'https://rickandmortyapi.com/api/episode/48'],
    gender: 'Male',
    id: 5,
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Jerry Smith',
    origin: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/5',
  },
  {
    created: '2017-11-04T19:50:28.250Z',
    episode: ['https://rickandmortyapi.com/api/episode/27'],
    gender: 'Female',
    id: 6,
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    location: { name: 'Mock Abadango', url: 'https://rickandmortyapi.com/api/location/2' },
    name: 'Mock Abadango Cluster Princess',
    origin: { name: 'Mock Abadango', url: 'https://rickandmortyapi.com/api/location/2' },
    species: 'Alien',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/6',
  },
  {
    created: '2017-11-04T19:59:20.523Z',
    episode: ['https://rickandmortyapi.com/api/episode/10', 'https://rickandmortyapi.com/api/episode/11'],
    gender: 'Male',
    id: 7,
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    location: { name: 'Mock Testicle Monster Dimension', url: 'https://rickandmortyapi.com/api/location/21' },
    name: 'Mock Abradolf Lincler',
    origin: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    species: 'Human',
    status: 'unknown',
    type: 'Genetic experiment',
    url: 'https://rickandmortyapi.com/api/character/7',
  },
  {
    created: '2017-11-04T20:03:34.737Z',
    episode: ['https://rickandmortyapi.com/api/episode/28'],
    gender: 'Male',
    id: 8,
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    location: { name: 'Mock Citadel of Ricks', url: 'https://rickandmortyapi.com/api/location/3' },
    name: 'Mock Adjudicator Rick',
    origin: { name: 'Mock unknown', url: '' },
    species: 'Human',
    status: 'Dead',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/8',
  },
  {
    created: '2017-11-04T20:06:54.976Z',
    episode: ['https://rickandmortyapi.com/api/episode/24'],
    gender: 'Male',
    id: 9,
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Agency Director',
    origin: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    species: 'Human',
    status: 'Dead',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/9',
  },
  {
    created: '2017-11-04T20:19:09.017Z',
    episode: ['https://rickandmortyapi.com/api/episode/25'],
    gender: 'Male',
    id: 10,
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    location: { name: "Worldender's lair", url: 'https://rickandmortyapi.com/api/location/4' },
    name: 'Mock Alan Rails',
    origin: { name: 'Mock unknown', url: '' },
    species: 'Human',
    status: 'Dead',
    type: 'Superhuman (Ghost trains summoner)',
    url: 'https://rickandmortyapi.com/api/character/10',
  },
  {
    created: '2017-11-04T20:20:20.965Z',
    episode: ['https://rickandmortyapi.com/api/episode/12'],
    gender: 'Male',
    id: 11,
    image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Albert Einstein',
    origin: { name: 'Mock Earth (C-137)', url: 'https://rickandmortyapi.com/api/location/1' },
    species: 'Human',
    status: 'Dead',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/11',
  },
  {
    created: '2017-11-04T20:32:33.144Z',
    episode: ['https://rickandmortyapi.com/api/episode/3'],
    gender: 'Male',
    id: 12,
    image: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
    location: { name: 'Mock Anatomy Park', url: 'https://rickandmortyapi.com/api/location/5' },
    name: 'Mock Alexander',
    origin: { name: 'Mock Earth (C-137)', url: 'https://rickandmortyapi.com/api/location/1' },
    species: 'Human',
    status: 'Dead',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/12',
  },
];
