import type { Character } from '@/types';

export const mockCharacters: Character[] = [
  {
    created: '2017-11-04T18:48:46.250Z',
    episode: ['https://rickandmortyapi.com/api/episode/1'],
    gender: 'Male',
    id: 1,
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    location: { name: 'Mock Citadel of Ricks', url: 'https://rickandmortyapi.com/api/location/3' },
    name: 'Mock Rick Sanchez',
    origin: { name: 'Mock Earth (C-137)', url: 'https://rickandmortyapi.com/api/location/1' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/1',
  },
  {
    created: '2017-11-04T18:50:21.651Z',
    episode: ['https://rickandmortyapi.com/api/episode/1'],
    gender: 'Male',
    id: 2,
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    location: { name: 'Mock Citadel of Ricks', url: 'https://rickandmortyapi.com/api/location/3' },
    name: 'Mock Morty Smith',
    origin: { name: 'Mock unknown', url: '' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/2',
  },
  {
    created: '2017-11-04T19:09:56.428Z',
    episode: ['https://rickandmortyapi.com/api/episode/6'],
    gender: 'Female',
    id: 3,
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Summer Smith',
    origin: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/3',
  },
  {
    created: '2017-11-04T19:22:43.665Z',
    episode: ['https://rickandmortyapi.com/api/episode/6'],
    gender: 'Female',
    id: 4,
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Beth Smith',
    origin: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    species: 'Human',
    status: 'Alive',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/4',
  },
  {
    created: '2017-11-04T20:20:20.965Z',
    episode: ['https://rickandmortyapi.com/api/episode/12'],
    gender: 'Male',
    id: 11,
    image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
    location: { name: 'Mock Earth (Replacement Dimension)', url: 'https://rickandmortyapi.com/api/location/20' },
    name: 'Mock Albert Einstein',
    origin: { name: 'Mock Earth (C-137)', url: 'https://rickandmortyapi.com/api/location/1' },
    species: 'Human',
    status: 'Dead',
    type: '',
    url: 'https://rickandmortyapi.com/api/character/11',
  },
];
