import type { TransformedCharacter } from '@/types';

export const mockTransformedCharacters: TransformedCharacter[] = [
  {
    gender: 'Male',
    id: '1',
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    info: [
      { label: 'Gender', value: 'Male' },
      { label: 'Origin', value: 'Earth (C-137)' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Alive' },
    ],
    name: 'Mock Rick Sanchez',
    origin: 'Mock Earth (C-137)',
    species: 'Human',
    status: 'Alive',
  },
  {
    gender: 'Male',
    id: '2',
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    info: [
      { label: 'Gender', value: 'Male' },
      { label: 'Origin', value: 'unknown' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Alive' },
    ],
    name: 'Mock Morty Smith',
    origin: 'Mock unknown',
    species: 'Human',
    status: 'Alive',
  },
  {
    gender: 'Female',
    id: '3',
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    info: [
      { label: 'Gender', value: 'Female' },
      { label: 'Origin', value: 'Earth (Replacement Dimension)' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Alive' },
    ],
    name: 'Mock Summer Smith',
    origin: 'Mock Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
  },
  {
    gender: 'Female',
    id: '4',
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    info: [
      { label: 'Gender', value: 'Female' },
      { label: 'Origin', value: 'Earth (Replacement Dimension)' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Alive' },
    ],
    name: 'Mock Beth Smith',
    origin: 'Mock Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
  },
  {
    gender: 'Male',
    id: '5',
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    info: [
      { label: 'Gender', value: 'Male' },
      { label: 'Origin', value: 'Earth (Replacement Dimension)' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Alive' },
    ],
    name: 'Mock Jerry Smith',
    origin: 'Mock Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
  },
  {
    gender: 'Female',
    id: '6',
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    info: [
      { label: 'Gender', value: 'Female' },
      { label: 'Origin', value: 'Abadango' },
      { label: 'Species', value: 'Alien' },
      { label: 'Status', value: 'Alive' },
    ],
    name: 'Mock Abadango Cluster Princess',
    origin: 'Mock Abadango',
    species: 'Alien',
    status: 'Alive',
  },
  {
    gender: 'Male',
    id: '7',
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    info: [
      { label: 'Gender', value: 'Male' },
      { label: 'Origin', value: 'Earth (Replacement Dimension)' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'unknown' },
    ],
    name: 'Mock Abradolf Lincler',
    origin: 'Mock Earth (Replacement Dimension)',
    species: 'Human',
    status: 'unknown',
  },
  {
    gender: 'Male',
    id: '8',
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    info: [
      { label: 'Gender', value: 'Male' },
      { label: 'Origin', value: 'unknown' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Dead' },
    ],
    name: 'Mock Adjudicator Rick',
    origin: 'Mock unknown',
    species: 'Human',
    status: 'Dead',
  },
  {
    gender: 'Male',
    id: '9',
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    info: [
      { label: 'Gender', value: 'Male' },
      { label: 'Origin', value: 'Earth (Replacement Dimension)' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Dead' },
    ],
    name: 'Mock Agency Director',
    origin: 'Mock Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Dead',
  },
  {
    gender: 'Male',
    id: '10',
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    info: [
      { label: 'Gender', value: 'Male' },
      { label: 'Origin', value: 'unknown' },
      { label: 'Species', value: 'Human' },
      { label: 'Status', value: 'Dead' },
    ],
    name: 'Mock Alan Rails',
    origin: 'Mock unknown',
    species: 'Human',
    status: 'Dead',
  },
];
